run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    - errorlint
    - gocritic
    - misspell
    - revive
    - unconvert
    - gofmt
    - goimports

issues:
  exclude-rules:
    - linters:
        - revive
      text: "should have a package comment"
    - linters:
        - revive
      text: "should have comment or be unexported"
    - path: _test\.go
      linters:
        - bodyclose
        - errcheck
